/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pegawai;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
/**
 *
 * @author selvitaa
 */
public class Transaksi_Pembayaran extends javax.swing.JFrame {
DefaultTableModel model;

    /**
     * Creates new form Transaksi
     */
    public Transaksi_Pembayaran() {
        initComponents();
        setSize(1300, 500); 
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Jual");
        model.addColumn("Jumlah");
        model.addColumn("Jenis Pembayaran");
        model.addColumn("Total");
        model.addColumn("Tanggal");

        jTable1.setModel(model);
        loadData();
    }
private void loadData() {
    try {
        Connection conn = DatabaseConnection.getConnection();
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM transaksi_pembayaran");

        // Kosongkan tabel terlebih dahulu
        model.setRowCount(0);

        while (rs.next()) {
            String id = rs.getString("id_transaksi");
            String kode = rs.getString("kode_barang");
            String nama = rs.getString("nama_barang");
            int harga = rs.getInt("harga_jual");
            int jumlah = rs.getInt("jumlah");
            String jenis = rs.getString("jenis_pembayaran");
            int total = rs.getInt("total");
            String tanggal = rs.getString("tanggal_transaksi");

            model.addRow(new Object[]{id, kode, nama, harga, jumlah, jenis, total, tanggal});
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data dari database.\n" + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DAFTAR TRANSAKSI PEGAWAI");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 10, 300, 25);

        jLabel1.setText("Id_Transaksi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 40, 120, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(135, 40, 228, 22);

        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 78, 120, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(135, 75, 228, 22);

        jLabel3.setText("Nama Barang ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 107, 120, 16);

        jLabel4.setText("Harga Jual");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 150, 120, 16);

        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 193, 120, 16);

        jLabel6.setText("Total");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 266, 120, 16);

        jLabel7.setText("Tanggal Transaksi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 295, 120, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aki Mobil Type Yuasa", "Aki Motor Type GS" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(135, 104, 228, 22);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(135, 147, 228, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(135, 190, 228, 22);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(135, 263, 228, 22);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(135, 292, 228, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(391, 40, 740, 216);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(135, 340, 228, 25);

        jLabel9.setText("Jenis Pembayaran");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(12, 233, 130, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunai", "Transfer" }));
        jComboBox2.setSelectedIndex(-1);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(135, 230, 228, 22);

        jMenu1.setText("Back");

        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText();
        String kode = jTextField2.getText();
        String nama = (String) jComboBox1.getSelectedItem();
        String hargaStr = jTextField3.getText();
        String jumlahStr = jTextField4.getText();
        String jenis = (String) jComboBox2.getSelectedItem();
        String tanggalStr = jTextField6.getText();

        if (id.isEmpty() || kode.isEmpty() || nama == null || hargaStr.isEmpty() || jumlahStr.isEmpty() || jenis == null || tanggalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int harga = Integer.parseInt(hargaStr);
            int jumlah = Integer.parseInt(jumlahStr);
            int total = harga * jumlah;
            jTextField5.setText(String.valueOf(total));

            // Konversi tanggal dari dd/MM/yyyy ke yyyy-MM-dd
            SimpleDateFormat sdfInput = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat sdfOutput = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = sdfInput.parse(tanggalStr);
            String tanggalSQL = sdfOutput.format(tanggal);
            
            Connection conn = DatabaseConnection.getConnection();
            String sqlCekStok = "SELECT stok FROM stok_barang WHERE kode_barang = ?";
            PreparedStatement pstCekStok = conn.prepareStatement(sqlCekStok);
            pstCekStok.setString(1, kode);
            ResultSet rsCek = pstCekStok.executeQuery();

            if (rsCek.next()) {
                int stokTersedia = rsCek.getInt("stok");
                if (jumlah > stokTersedia) {
                    JOptionPane.showMessageDialog(this, "Stok tidak mencukupi untuk transaksi ini!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data stok barang tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String sql = "INSERT INTO transaksi_pembayaran "
           + "(kode_barang, nama_barang, harga_jual, jumlah, "
           + " jenis_pembayaran, total, tanggal_transaksi) "
           + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, kode);
            stmt.setString(2, nama);
            stmt.setInt(3, harga);
            stmt.setInt(4, jumlah);
            stmt.setString(5, jenis);
            stmt.setInt(6, total);
            stmt.setString(7, tanggalSQL);
            
            String sqlPenjualan = "INSERT INTO transaksi_penjualan "
            + "(kode_barang, nama_barang, harga_jual, jumlah, total, tanggal_transaksi) "
            + "VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstPenj = conn.prepareStatement(sqlPenjualan);
            pstPenj.setString(1, kode);
            pstPenj.setString(2, nama);
            pstPenj.setInt(3, harga);
            pstPenj.setInt(4, jumlah);
            pstPenj.setInt(5, total);
            pstPenj.setString(6, tanggalSQL);
            pstPenj.executeUpdate();
            
            String sqlUpdateStok = "UPDATE stok_barang SET stok = stok - ? WHERE kode_barang = ?";
            PreparedStatement pstStok = conn.prepareStatement(sqlUpdateStok);
            pstStok.setInt(1, jumlah); // jumlah barang yang dibeli
            pstStok.setString(2, kode);
            pstStok.executeUpdate();

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                model.addRow(new Object[]{id, kode, nama, harga, jumlah, jenis, total, tanggalSQL});
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database.");
            }
           
            // Reset form
            jTextField1.setText("");
            jTextField2.setText("");
            jComboBox1.setSelectedIndex(-1);
            jTextField3.setText("");
            jTextField4.setText("");
            jComboBox2.setSelectedIndex(-1);
            jTextField5.setText("");
            jTextField6.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga dan Jumlah harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal salah. Gunakan format dd/MM/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new DashboardPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi_Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
